server:
  port: 8010

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qffd?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml